<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [2]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [5]:
%%sql

SELECT
  p.categoryname AS category,
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (s.quantity * s.netprice *s.exchangerate)) AS median_sales
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY p.categoryname
ORDER BY p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  median_sales
0                          Audio        219.59
1        Cameras and camcorders         730.74
2                    Cell phones        459.88
3                      Computers        982.44
4                 Games and Toys         34.10
5                Home Appliances        696.08
6  Music, Movies and Audio Books        152.80
7                   TV and Video        682.83

In [12]:
%%sql

SELECT
  p.categoryname AS category,
  PERCENTILE_CONT(0.5) WITHIN GROUP (
  ORDER BY
  (CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END)
  ) AS median_sales_2022
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY p.categoryname
ORDER BY p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  median_sales_2022
0                          Audio             257.21
1        Cameras and camcorders              651.46
2                    Cell phones             418.60
3                      Computers             809.70
4                 Games and Toys              33.78
5                Home Appliances             791.00
6  Music, Movies and Audio Books             186.58
7                   TV and Video             730.46

In [30]:
%%sql

WITH median_value AS (
  SELECT
    PERCENTILE_CONT(0.5) WITHIN GROUP
    (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS median
  FROM sales s
)

SELECT
  p.categoryname AS category,
  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) < mv.median
  AND s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
  THEN (s.quantity * s.netprice * s.exchangerate) END) AS low_net_revenue_2022,
  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) >= mv.median
  AND s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
  THEN (s.quantity * s.netprice * s.exchangerate) END) AS high_net_revenue_2022,
  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) < mv.median
  AND s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
  THEN (s.quantity * s.netprice * s.exchangerate) END) AS low_net_revenue_2023,
  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) >= mv.median
  AND s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
  THEN (s.quantity * s.netprice * s.exchangerate) END) AS high_net_revenue_2023 -- 计算高于中位数的的销售总额
FROM
  sales s
  LEFT JOIN product p ON s.productkey = p.productkey,
  median_value mv -- 子查询
GROUP BY p.categoryname
ORDER BY p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,low_net_revenue_2022,high_net_revenue_2022,low_net_revenue_2023,high_net_revenue_2023
0,Audio,223932.63,543005.58,181847.01,506843.18
1,Cameras and camcorders,133801.07,2248731.49,105268.50,1878277.79
2,Cell phones,822810.73,7296854.34,738857.59,5263290.05
3,Computers,626333.55,17235879.94,592385.19,11058482.02
4,Games and Toys,232378.35,83748.95,206103.36,64271.60
5,Home Appliances,220196.04,6392250.64,177059.16,5742933.71
6,"Music, Movies and Audio Books",687403.38,2301893.90,576552.89,1604215.24
7,TV and Video,273532.94,5541803.66,166265.95,4245912.27

In [45]:
%%sql

WITH perc_group AS (
  SELECT
    PERCENTILE_CONT(0.25) WITHIN GROUP
    (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS low_perc,
    PERCENTILE_CONT(0.75) WITHIN GROUP
    (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS high_perc
  FROM sales s
  WHERE
    orderdate BETWEEN '2022-01-01' AND '2023-12-31'
)

SELECT
  p.categoryname AS category,
  CASE
    WHEN (s.quantity * s.netprice * s.exchangerate) <= perc.low_perc THEN '1-LOW'
    WHEN (s.quantity * s.netprice * s.exchangerate) >= perc.high_perc THEN '3-HIGH'
    ELSE '2-MEDIAM' END AS revenue_tier,
  SUM(s.quantity * s.netprice * s.exchangerate) AS total_revenue
FROM
  sales s
  LEFT JOIN product p ON s.productkey = p.productkey,
  perc_group perc -- 子查询
GROUP BY p.categoryname,revenue_tier
ORDER BY p.categoryname
-- 将销售额按高低排序后，根据在所有数据中的占比分类

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

                         category revenue_tier  total_revenue
0                           Audio        1-LOW      267217.01
1                           Audio     2-MEDIAM     3832415.38
2                           Audio       3-HIGH     1213265.71
3         Cameras and camcorders         1-LOW       81032.92
4         Cameras and camcorders      2-MEDIAM     3388546.10
5         Cameras and camcorders        3-HIGH    15050781.63
6                     Cell phones        1-LOW      410309.35
7                     Cell phones     2-MEDIAM    10338963.22
8                     Cell phones       3-HIGH    21874993.15
9                       Computers        1-LOW      203207.06
10                      Computers     2-MEDIAM    10808054.11
11                      Computers       3-HIGH    79607760.89
12                 Games and Toys        1-LOW      533443.13
13                 Games and Toys     2-MEDIAM     1001381.91
14                 Games and Toys       3-HIGH      133749.09
15                Home Appliances        1-LOW      105045.60
16                Home Appliances     2-MEDIAM     4118724.64
17                Home Appliances       3-HIGH    22383475.30
18  Music, Movies and Audio Books        1-LOW      642496.71
19  Music, Movies and Audio Books     2-MEDIAM     6100817.99
20  Music, Movies and Audio Books       3-HIGH     3844996.29
21                   TV and Video        1-LOW       67221.76
22                   TV and Video     2-MEDIAM     3766783.30
23                   TV and Video       3-HIGH    16632856.33

In [ ]:
%%sql

SELECT
  orderdate,
  DATE_TRUNC('month',orderdate)::date AS order_month
   -- 将符合条件的日期按时间戳的方式显示，::date表示将时间戳转为日期格式
FROM sales
ORDER BY RANDOM()
LIMIT 10

In [52]:
%%sql

SELECT
  EXTRACT('year' FROM orderdate) AS order_date_yearly,
  EXTRACT('month' FROM orderdate) AS order_date_monthly,
  SUM(quantity * netprice * exchangerate) AS total_revenue,
  COUNT(DISTINCT customerkey) AS total_unique_customers
   -- 将符合条件的日期按时间戳的方式显示，::date表示将时间戳转为日期格式
  -- DATE_PART('year',orderdate) -- 将日期的年、月、日提取出来，转为小数
  -- EXTRACT('year' FROM orderdate) -- 将日期的年、月、日提取出来,转为字符串
FROM sales
GROUP BY order_date_yearly,order_date_monthly
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  order_date_yearly order_date_monthly  total_revenue  total_unique_customers
0              2015                  1      384092.66                     200
1              2015                  2      706374.12                     291
2              2015                  3      332961.59                     139
3              2015                  4      160767.00                      78
4              2015                  5      548632.63                     236
5              2015                  6      748563.97                     238
6              2015                  7      635376.13                     227
7              2015                  8      718538.62                     235
8              2015                  9      696805.68                     277
9              2015                 10      824891.22                     304

In [54]:
%%sql

SELECT
  CURRENT_DATE,
  orderdate,
  AGE(CURRENT_DATE,orderdate) -- AGE()函数计算CURRENT_DATE和orderdate的间隔
  -- INTERVAL '5 years' 显示5年间隔的时间
FROM sales
WHERE orderdate >= CURRENT_DATE - INTERVAL '5 years' -- 查找近5年的数据
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  current_date   orderdate       age
0   2026-03-11  2021-03-11 1825 days
1   2026-03-11  2021-03-11 1825 days
2   2026-03-11  2021-03-11 1825 days
3   2026-03-11  2021-03-11 1825 days
4   2026-03-11  2021-03-11 1825 days
5   2026-03-11  2021-03-11 1825 days
6   2026-03-11  2021-03-11 1825 days
7   2026-03-11  2021-03-11 1825 days
8   2026-03-11  2021-03-11 1825 days
9   2026-03-11  2021-03-11 1825 days

In [61]:
%%sql

SELECT
  DATE_PART('year',orderdate) AS order_year,
  ROUND(AVG(EXTRACT(DAYS FROM AGE(deliverydate,orderdate))),2) AS avg_processing_time
FROM sales
GROUP BY
  order_year
ORDER BY
  avg_processing_time
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   order_year avg_processing_time
0     2019.00                0.81
1     2017.00                0.83
2     2018.00                0.86
3     2020.00                0.93
4     2016.00                1.08
5     2015.00                1.10
6     2021.00                1.36
7     2022.00                1.62
8     2024.00                1.67
9     2023.00                1.75

In [66]:
%%sql

SELECT
  customerkey,
  orderkey,
  linenumber,
  (quantity * netprice * exchangerate) as net_revenue,
  ROW_NUMBER() OVER (
    PARTITION BY customerkey
    ORDER BY quantity * netprice * exchangerate DESC

  ) AS order_rank,
  -- ROW_NUMBER函数可以给显示结果中的分组（此例用customerkey分组）内的每一行标注行号，进行排序后相当于排名
  SUM(quantity * netprice * exchangerate) OVER(
    PARTITION BY customerkey
    ORDER BY orderdate
  ) AS customer_running_total

FROM sales
LIMIT 10
-- 窗口函数，可以不写GROUP BY 语句，单独将聚合函数的计算结果显示在分组中

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   customerkey  orderkey  linenumber  net_revenue  customer_running_total
0           15   2259001           0      2217.41                 2217.41
1          180   1305016           0       525.31                  525.31
2          180   3162018           0        71.36                 2510.22
3          180   3162018           1      1913.55                 2510.22
4          185   1613010           0      1395.52                 1395.52
5          243    505008           0       287.67                  287.67
6          387   1451007           0      1608.10                 2370.54
7          387   1451007           2        97.05                 2370.54
8          387   1451007           3        45.62                 2370.54
9          387   1451007           1       619.77                 2370.54

In [76]:
%%sql

SELECT
  orderdate,
  orderkey *10 + linenumber AS order_line_number,
  (quantity * netprice * exchangerate) as net_revenue,
  SUM(quantity * netprice * exchangerate) OVER(
    PARTITION BY orderdate
  ) AS daily_net_revenue,
  (quantity * netprice * exchangerate)*100/SUM(quantity * netprice * exchangerate) OVER(PARTITION BY orderdate) AS pct_daily_revenue
FROM sales
LIMIT 10
-- 窗口函数，可以不写GROUP BY 语句，单独将聚合函数的计算结果显示在表中，不会像GROUP BY 那样把相同组名的合并为一列

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,order_line_number,net_revenue,daily_net_revenue,pct_daily_revenue
0,2015-01-01,10000,63.49,11640.80,0.55
1,2015-01-01,10001,423.28,11640.80,3.64
2,2015-01-01,10010,108.75,11640.80,0.93
3,2015-01-01,10020,1146.75,11640.80,9.85
4,2015-01-01,10021,950.25,11640.80,8.16
5,2015-01-01,10022,1302.91,11640.80,11.19
6,2015-01-01,10023,58.73,11640.80,0.50
7,2015-01-01,10030,224.98,11640.80,1.93
8,2015-01-01,10040,263.11,11640.80,2.26
9,2015-01-01,10041,578.52,11640.80,4.97

In [83]:
%%sql

WITH yearly_cohort AS (
  SELECT DISTINCT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate) OVER(PARTITION BY customerkey)) AS cohort_year
FROM sales
-- 获得某客户第一次订购商品的年份
)
SELECT
  yc.cohort_year,
  EXTRACT(YEAR FROM orderdate) AS purchase_year,
  SUM(s.quantity * s.netprice * s.exchangerate) AS net_revenue
FROM sales s
LEFT JOIN yearly_cohort yc ON s.customerkey = yc.customerkey
GROUP BY
  yc.cohort_year,
  purchase_year
-- 获取客户在不同年份的购买额对比

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

   cohort_year purchase_year  net_revenue
0         2015          2015   7370979.48
1         2015          2016    392623.48
2         2015          2017    479841.31
3         2015          2018   1069850.87
4         2015          2019   1235991.48
5         2015          2020    386489.60
6         2015          2021    872845.99
7         2015          2022   1569787.72
8         2015          2023   1157633.91
9         2015          2024    356186.62
10        2016          2016   9990990.20
11        2016          2017    497028.11
12        2016          2018   1074607.29
13        2016          2019   1565400.72
14        2016          2020    474087.09
15        2016          2021    964417.85
16        2016          2022   2164681.10
17        2016          2023   1265242.63
18        2016          2024    364066.76
19        2017          2017  12244469.63
20        2017          2018   1407065.13
21        2017          2019   1764716.90
22        2017          2020    625928.03
23        2017          2021   1329858.72
24        2017          2022   2428882.80
25        2017          2023   1714010.18
26        2017          2024    464802.56
27        2018          2018  21115924.55
28        2018          2019   3229188.22
29        2018          2020   1171126.65
30        2018          2021   2201262.39
31        2018          2022   4534295.81
32        2018          2023   3271753.92
33        2018          2024    936833.89
34        2019          2019  24022798.65
35        2019          2020   1295044.99
36        2019          2021   2337594.77
37        2019          2022   4848980.74
38        2019          2023   3440099.20
39        2019          2024    751725.53
40        2020          2020   7265759.44
41        2020          2021   1016399.07
42        2020          2022   1891708.40
43        2020          2023   1435051.04
44        2020          2024    312983.02
45        2021          2021  12635597.87
46        2021          2022   3014082.50
47        2021          2023   2242369.63
48        2021          2024    495686.18
49        2022          2022  24412138.13
50        2022          2023   4237220.04
51        2022          2024   1223450.12
52        2023          2023  14345184.96
53        2023          2024    634143.37
54        2024          2024   2856649.33

In [95]:
%%sql

WITH yearly_cohort AS (
  SELECT DISTINCT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate) OVER(PARTITION BY customerkey)) AS cohort_year,
    EXTRACT(YEAR FROM orderdate) AS purchase_year
FROM sales
-- 获得某客户第一次订购商品的年份
)
SELECT DISTINCT
  yc.cohort_year,
  yc.purchase_year,
  COUNT(s.customerkey) OVER(PARTITION BY yc.purchase_year,yc.cohort_year) AS num_customers
FROM sales s
LEFT JOIN yearly_cohort yc ON s.customerkey = yc.customerkey
ORDER BY
  yc.cohort_year,
  yc.purchase_year

-- 获取不同年份的客户数量对比

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

   cohort_year purchase_year  num_customers
0         2015          2015          14128
1         2015          2016           1032
2         2015          2017           1177
3         2015          2018           2733
4         2015          2019           2977
5         2015          2020           1391
6         2015          2021           2319
7         2015          2022           4750
8         2015          2023           4012
9         2015          2024           1137
10        2016          2016          16260
11        2016          2017           1306
12        2016          2018           2737
13        2016          2019           3409
14        2016          2020           1539
15        2016          2021           2521
16        2016          2022           5622
17        2016          2023           4181
18        2016          2024           1370
19        2017          2017          19909
20        2017          2018           3508
21        2017          2019           4238
22        2017          2020           1812
23        2017          2021           3544
24        2017          2022           7157
25        2017          2023           5730
26        2017          2024           2000
27        2018          2018          34414
28        2018          2019           7749
29        2018          2020           3432
30        2018          2021           5740
31        2018          2022          11568
32        2018          2023          10137
33        2018          2024           3283
34        2019          2019          33792
35        2019          2020           3789
36        2019          2021           6010
37        2019          2022          11593
38        2019          2023           9973
39        2019          2024           2600
40        2020          2020          12148
41        2020          2021           2359
42        2020          2022           4370
43        2020          2023           3535
44        2020          2024           1106
45        2021          2021          17920
46        2021          2022           6332
47        2021          2023           5447
48        2021          2024           1696
49        2022          2022          31112
50        2022          2023          10045
51        2022          2024           3305
52        2023          2023          16754
53        2023          2024           1719
54        2024          2024           3436

In [98]:
%%sql

WITH yearly_cohort AS (
  SELECT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate)) AS cohort_year,
    SUM(quantity * netprice * exchangerate) AS customer_ltv
    -- 该客户为公司创造的总收入 lifetime value （LTV）
  FROM
    sales
  GROUP BY
    customerkey

)
SELECT
  *,
  AVG(customer_ltv) OVER (PARTITION BY cohort_year) AS avg_cohort_ltv
FROM
  yearly_cohort

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey cohort_year  customer_ltv  avg_cohort_ltv
0          1490547        2015        271.35         5271.59
1           651155        2015       2070.85         5271.59
2          1109495        2015       2313.29         5271.59
3           166453        2015        944.89         5271.59
4          1326661        2015       3603.93         5271.59
...            ...         ...           ...             ...
49482      1303362        2024        278.00         2037.55
49483      1273016        2024       2138.57         2037.55
49484       823755        2024       1955.84         2037.55
49485       657822        2024         18.93         2037.55
49486      1438446        2024       3306.04         2037.55

[49487 rows x 4 columns]

In [102]:
%%sql

SELECT
  customerkey,
  orderdate,
  (quantity * netprice * exchangerate) as net_revenue,
  COUNT(*) OVER(
    PARTITION BY customerkey
    ORDER BY orderdate
  ) AS running_order_count,
  AVG(quantity * netprice * exchangerate) OVER(
    PARTITION BY customerkey
    ORDER BY orderdate
  ) AS running_avg_revenue
FROM sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,customerkey,orderdate,net_revenue,running_order_count,running_avg_revenue
0,15,2021-03-08,2217.41,1,2217.41
1,180,2018-07-28,525.31,1,525.31
2,180,2023-08-28,71.36,3,836.74
3,180,2023-08-28,1913.55,3,836.74
4,185,2019-06-01,1395.52,1,1395.52
...,...,...,...,...,...
199868,2099711,2016-08-13,2067.75,1,2067.75
199869,2099711,2017-08-14,3940.92,2,3004.34
199870,2099743,2022-03-17,375.57,2,234.81
199871,2099743,2022-03-17,94.05,2,234.81
199872,2099743,2023-02-11,598.46,3,356.03

In [110]:
%%sql
WITH row_numbering AS(
  SELECT
    ROW_NUMBER() OVER(
      PARTITION BY orderdate
      ORDER BY
        orderdate,
        orderkey,
        linenumber
    ) AS row_num,
    *
  FROM sales
)

SELECT *
FROM row_numbering

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,row_num,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,2,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,3,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,4,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,5,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199868,93,3398034,1,2024-04-20,2024-04-21,664396,999999,1651,7,159.99,139.19,73.57,EUR,0.94
199869,94,3398034,2,2024-04-20,2024-04-21,664396,999999,1646,1,159.99,159.99,73.57,EUR,0.94
199870,95,3398035,0,2024-04-20,2024-04-22,267690,999999,1575,2,60.99,53.67,28.05,CAD,1.38
199871,96,3398035,1,2024-04-20,2024-04-22,267690,999999,415,5,326.00,293.40,166.20,CAD,1.38
199872,97,3398035,2,2024-04-20,2024-04-22,267690,999999,1693,6,6.88,6.88,3.16,CAD,1.38

In [114]:
%%sql

SELECT
  customerkey,
  COUNT(*) AS total_orders,
  ROW_NUMBER() OVER(ORDER BY COUNT(*) DESC) AS total_orders_row_num,
  -- 给每一行提供一个不重复的行号
  RANK() OVER(ORDER BY COUNT(*) DESC) AS total_orders_rank
  -- 给每一行提供一个排名，若排行的值有重复，会给予相同的排名，但排名的总数不会减少，会设定为排行的行数
  DENSE_RANK() OVER(ORDER BY COUNT(*) DESC) AS total_orders_rank
  -- 给每一行提供一个排名，若排行的值有重复，会给予相同的排名，但排名的总数也会减少
FROM sales
GROUP BY customerkey
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   customerkey  total_orders  total_orders_row_num  total_orders_rank
0      1834524            31                     1                  1
1      1375597            30                     2                  2
2       249557            27                     3                  3
3       459519            26                     4                  4
4      1495941            26                     5                  4
5      1801215            26                     6                  4
6      1219056            25                     7                  7
7       759419            24                     8                  8
8      1427444            24                     9                  8
9      1876222            24                    10                  8

In [129]:
%%sql

WITH monthly_revenue AS (
  SELECT
    TO_CHAR(orderdate,'YYYY-MM') AS month,
    SUM(quantity * netprice * exchangerate) AS net_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY month
  ORDER BY month

)
SELECT
  *,
  # # FIRST_VALUE(net_revenue) OVER (ORDER BY month) AS first_month_revenue,
  # # -- 获取表格的第一行数据
  # # LAST_VALUE(net_revenue) OVER
  # # (ORDER BY month ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS first_month_revenue,
  # # -- 获取表格的最后一行数据
  # # NTH_VALUE(net_revenue,3) OVER (ORDER BY month) AS first_month_revenue,
  # # -- 获取表格的某一行数据
  LAG(net_revenue) OVER (ORDER BY month) AS first_month_revenue,
  # # -- 根据给予的偏移量，获得当前行前面n行的数据
  # # LEAD(net_revenue) OVER (ORDER BY month) AS first_month_revenue,
  # # -- 根据给予的偏移量，获得当前行后面n行的数据
  (net_revenue - LAG(net_revenue) OVER (ORDER BY month)) /
  LAG(net_revenue) OVER (ORDER BY month) AS first_month_revenue
FROM monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  first_month_revenue  first_month_revenue
0   2023-01   3664431.34                  NaN                  NaN
1   2023-02   4465204.57           3664431.34                 0.22
2   2023-03   2244316.52           4465204.57                -0.50
3   2023-04   1162796.16           2244316.52                -0.48
4   2023-05   2943005.99           1162796.16                 1.53
5   2023-06   2864500.03           2943005.99                -0.03
6   2023-07   2337639.34           2864500.03                -0.18
7   2023-08   2623919.79           2337639.34                 0.12
8   2023-09   2622774.85           2623919.79                -0.00
9   2023-10   2551322.61           2622774.85                -0.03
10  2023-11   2700103.38           2551322.61                 0.06
11  2023-12   2928550.93           2700103.38                 0.08

In [140]:
%%sql

WITH monthly_revenue AS (
  SELECT
    TO_CHAR(orderdate,'YYYY-MM') AS month,
    SUM(quantity * netprice * exchangerate) AS net_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY month
  ORDER BY month

)

SELECT
  *,
  AVG(net_revenue) OVER (
    ORDER BY month
    ROWS BETWEEN CURRENT ROW AND CURRENT ROW
    -- 决定窗口的范围，使窗口函数计算时，只需要用当前行的数据计算
    # 不限制窗口的范围的话，会导致在第二行用第一行与第二行的数据一起计算，在第三行用第三行、第二行和第一行的数据进行计算
    ROWS BETWEEN 1 PRECEDING AND CURRENT ROW
    -- 决定窗口的范围，使窗口函数计算时，PRECEDING使用当前行和前面1行进行计算
    ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING
    -- 决定窗口的范围，使窗口函数计算时，PRECEDING使用当前行和后面1行进行计算
    -- 数字改成UNBOUNDED则不限制行数，会取当前行与前面所有行或者当前行与后面所有行进行计算

  ) AS avg_net_revenue_monthly
FROM monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  avg_net_revenue_monthly
0   2023-01   3664431.34               4064817.96
1   2023-02   4465204.57               3354760.54
2   2023-03   2244316.52               1703556.34
3   2023-04   1162796.16               2052901.08
4   2023-05   2943005.99               2903753.01
5   2023-06   2864500.03               2601069.68
6   2023-07   2337639.34               2480779.57
7   2023-08   2623919.79               2623347.32
8   2023-09   2622774.85               2587048.73
9   2023-10   2551322.61               2625712.99
10  2023-11   2700103.38               2814327.15
11  2023-12   2928550.93               2928550.93